### ISSUE TITLE
WGLC: Requirements for Port Prefix Naming

### ISSUE THREAD

**Issue by MikeBishop** [tlswg/draft-ietf-tls-svcb-ech#3]
Raghu Saxena [previously raised](https://mailarchive.ietf.org/arch/msg/tls/ynRkX60dGq-ofmSW4POhppQcgkY/) this issue:

> I was wondering if it may be useful to use stronger language in the draft to indicate a client MUST use Port Prefix Naming when looking up the SVCB record.

**Comment by MikeBishop** [comment]
As this document is not a protocol mapping, but simply the definition of a SvcParam which could be used by any protocol mapping, I don’t believe mandating anything about how mappings construct their names is appropriate here.

**Comment by enygren** [comment]
Agreed, I think this doesn't need fixing.
